### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by matanel-y** [maxplanck-ie/HiCBrowser#29]
Hello,

I was wondering if this is still supported or not.  I have had issues installing and getting the browser running. the runBrowser command cannot find trackPlot.py in hicexplorer and indeed it does not exist there. Is there another way to use this program?

Thanks

**Comment by vivekbhr** [comment]
Hi @matanel-y . We stopped further development of HiCBrowser after 2019, since [HiGlass](https://higlass.io/) provides a feature-rich and actively supported alternative, and HiCExplorer files are compatible with it. However the current release it still stable if you use an older version of HiCExplorer (v1.8). Since version 2.0, Trackplot.py has been moved to [pygenometracks](https://github.com/deeptools/pyGenomeTracks), which is also actively-maintained, but the HiCBrowser codebase has not been updated to reflect that.
